Repository OBOFoundry/OBOFoundry.github.io, pull requests merged in 2022-06, with the labels that each got.

#1896 Add publication as requested
  ontology/gno.md
Labels: submitter action needed

#1831 Add publication to eupath
  ontology/eupath.md
Labels: attn: OFOC call, blocked, submitter action needed

#1966 De-duplicate ontology descriptions
  ontology/aism.md
  ontology/apo.md
  ontology/cheminf.md
  ontology/cto.md
  ontology/fbbi.md
  ontology/hao.md
  ontology/mamo.md
  ontology/mpath.md
  ontology/oarcs.md
  ontology/ohmi.md
  ontology/opmi.md
  ontology/rs.md
  ontology/spd.md
  ontology/wbbt.md
  ontology/wbls.md
  ontology/wbphenotype.md
  tests/test_integrity.py
Labels: scheduled-merge
