Repository OBOFoundry/OBOFoundry.github.io, pull requests merged in 2022-01, with the labels that each got.

#1686 Add minimal `tox.ini` to demonstate future potential code quality checking.
  .github/workflows/qa.yml
  tox.ini
  util/create-html-grid.py
  util/sort-ontologies.py
  util/validate-metadata.py
Labels: pipeline, quality checks, attn: Technical WG

#1772 registry/ontologies.yaml -> ontologies.yml
  README-sitedev.md
Labels: documentation

#1771 Ensure future ontologies conform to FP-001
  util/schema/registry_schema.json
  util/validate-metadata.py
Labels: automated validation of principles
