Repository OBOFoundry/OBOFoundry.github.io, pull requests merged in 2022-08, with the labels that each got.

#1978 Search sort filter table
  README-sitedev.md
  _includes/js/custom.js
  _includes/js/jquery-ui.js
  _includes/js/sorttable.js
  _includes/ontology_table.html
  _includes/table_widget.html
  _includes/themes/bootstrap-3/default.html
  css/custom.css
  css/jquery-ui.css
  docker-compose.yml
  index.html
  js/all.js
Labels: usability feature, attn: OFOC call

#2035 Deactivate sort by foundry status
  util/validate-metadata.py
Labels: attn: OFOC call

#2055 Improve page titles
  _config.yml
  _config_header.yml
  docs/COC.md
  docs/Citation.md
  docs/CommitteeMeetings.md
  docs/CompletedReviews.md
  docs/EditorialWG.md
  docs/MailingLists.md
  docs/Membership.md
  docs/MissionStatement.md
  docs/OBOCalendar.md
  docs/OntologyStatus.md
  docs/OperationsCommitteePolicyDecisions.md
  docs/OutreachWG.md
  docs/PrinciplesReviewWorkflow.md
  docs/RegistrationChecklist.md
  docs/Related_Projects.md
  docs/ReservePrefix.md
  docs/ReviewCriteriaPolicies.md
  docs/ReviewManagementGuidelines.md
  docs/ReviewProcessGuidelines.md
  docs/SOP.md
  docs/TableOfContents.md
  docs/TechnicalWG.md
  docs/TechnicalWGMeetings.md
  pages.md
  post-templates/YYYY-MM-DD-announce-new-foundry-ontology.md
  registry/publications.md
Labels: website

#2064 Improve home page column spacing
  _includes/js/custom.js
Labels: website

#2066 Update citation display
  _layouts/ontology_detail.html
Labels: website

#2070 Add badge for preferred citations
  _layouts/ontology_detail.html
  ontology/eco.md
  ontology/fbbt.md
  tests/test_integrity.py
  util/schema/registry_schema.json
Labels: website

#2069 Add display of repository when different from homepage
  _layouts/ontology_detail.html
  ontology/eco.md
Labels: website
