Repository OBOFoundry/OBOFoundry.github.io, pull requests merged in 2022-11, with the labels that each got.

#2175 Add IDO and CIDO publications
  ontology/cido.md
  ontology/ido.md
Labels: ontology metadata, specific ontology

#2177 Adding OBO Google Service Manager to roles.yml
  _data/roles.yml
Labels: attn: OFOC call

#2171 Add publication for OGMS
  ontology/ogms.md
Labels: ontology metadata, specific ontology

#2198 First draft of a general Roles SOP
  docs/roles/OBORoles.md
Labels: attn: OFOC call

#2206 Improve organization of roles pages
  _includes/docs_toc.md
  _includes/header.html
  docs/Membership.md
  docs/roles/OBORoles.md
  docs/roles/overview.md
Labels: website
