Repository OBOFoundry/OBOFoundry.github.io, pull requests merged in 2023-02, with the labels that each got.

#2288 Added hard-coded pipe symbols to TOC in fp-011-locus-of-authority.md
  principles/fp-011-locus-of-authority.md
Labels: website

#2289 Removes any mild implication of Foundry vs Library status in fp-001-o…
  principles/fp-001-open.md
Labels: website

#2267 Adding twitter handle for CL
  ontology/cl.md
Labels: ontology metadata

#2292 Add TOC to p2
  principles/fp-002-format.md
Labels: website

#2293 Add TOC to p3
  principles/fp-003-uris.md
Labels: website

#2294 Add TOC to p4
  principles/fp-004-versioning.md
Labels: website

#2295 Add TOC for p6
  principles/fp-006-textual-definitions.md
Labels: website

#2296 Add TOC to p9
  principles/fp-009-users.md
Labels: website

#2297 Add TOC to p13
  principles/fp-013-notification.md
Labels: website

#2298 Add TOC to p20
  principles/fp-020-responsiveness.md
Labels: website

#2256 add text about ontology acceptance/rejection decision process
  docs/SOP.md
Labels: attn: OFOC call

#1841 Require new ontologies include a link to contribution guidelines
  .github/ISSUE_TEMPLATE/new-ontology.yml
  tests/test_integrity.py
Labels: ontology metadata, principles, automated validation of principles

#2279 Automated check of passing NOR dashboard
  tests/test_integrity.py
Labels: automated validation of principles
