Repository OBOFoundry/OBOFoundry.github.io, pull requests merged in 2023-06, with the labels that each got.

#2377 Update repository field for VariO
  ontology/vario.md
  util/validate-metadata.py
Labels: specific ontology, awaiting external review

#2311 Use canonical OGMS publication
  ontology/ogms.md
Labels: specific ontology

#2319 Add SOP for reviving obsolete, orphaned, or inactive ontologies
  docs/SOP.md
Labels: policy, attn: OFOC call

#2391 Improve newsletter
  CONTRIBUTING.md
  _data/roles.yml
  _includes/header.html
  _layouts/post.html
  _posts/2023-06-16-inaugural-newsletter.md
Labels: website

#2386 Create new role: OBO Slack Community Manager
  _data/roles.yml
Labels: newsletter

#2368 Create mcro.md
  ontology/mcro.md
Labels: new ontology - submitter action needed

#2387 Add new role: OBO Code of Coduct Committee Member
  _data/roles.yml
Labels: newsletter
